export const LOGIN_COPY = {
    en: {
        back: 'Back to Home',
        title: 'Operator Login',
        desc: 'Sign in with your registered phone number to access the claims dashboard.',
        sendOtp: 'Send OTP',
        phoneError: 'Enter a valid 10-digit phone number',
        otpSent: 'OTP sent to',
        enterOtp: 'Enter OTP',
        otpError: 'Enter the 6-digit OTP',
        verify: 'Verify & Login',
        resend: 'Change number / Resend OTP',
        verifying: 'Verifying OTP...',
        footer: 'Secured by AWS Cognito. OTP verified via Twilio.',
        sendFailed: 'Failed to send OTP',
        verifyFailed: 'Verification failed',
    },
    hi: {
        back: 'होम पर वापस जाएं',
        title: 'ऑपरेटर लॉगिन',
        desc: 'क्लेम डैशबोर्ड खोलने के लिए अपने रजिस्टर्ड फोन नंबर से साइन इन करें।',
        sendOtp: 'OTP भेजें',
        phoneError: 'कृपया सही 10 अंकों का फोन नंबर दर्ज करें',
        otpSent: 'OTP भेजा गया',
        enterOtp: 'OTP दर्ज करें',
        otpError: 'कृपया 6 अंकों का OTP दर्ज करें',
        verify: 'सत्यापित करें और लॉगिन करें',
        resend: 'नंबर बदलें / OTP फिर भेजें',
        verifying: 'OTP सत्यापित किया जा रहा है...',
        footer: 'AWS Cognito द्वारा सुरक्षित। OTP Twilio से सत्यापित होता है।',
        sendFailed: 'OTP भेजा नहीं जा सका',
        verifyFailed: 'सत्यापन विफल रहा',
    },
    mr: {
        back: 'मुख्यपृष्ठावर परत जा',
        title: 'ऑपरेटर लॉगिन',
        desc: 'क्लेम डॅशबोर्ड वापरण्यासाठी तुमच्या नोंदणीकृत फोन नंबरने साइन इन करा.',
        sendOtp: 'OTP पाठवा',
        phoneError: 'वैध 10 अंकी फोन नंबर टाका',
        otpSent: 'OTP पाठवला आहे',
        enterOtp: 'OTP टाका',
        otpError: '6 अंकी OTP टाका',
        verify: 'पडताळा आणि लॉगिन करा',
        resend: 'नंबर बदला / OTP पुन्हा पाठवा',
        verifying: 'OTP पडताळला जात आहे...',
        footer: 'AWS Cognito द्वारे सुरक्षित. OTP Twilio द्वारे पडताळला जातो.',
        sendFailed: 'OTP पाठवता आला नाही',
        verifyFailed: 'पडताळणी अयशस्वी झाली',
    },
    te: {
        back: 'హోమ్‌కు తిరిగి వెళ్ళండి',
        title: 'ఆపరేటర్ లాగిన్',
        desc: 'క్లెయిమ్ డ్యాష్‌బోర్డ్ కోసం మీ నమోదిత ఫోన్ నంబర్‌తో సైన్ ఇన్ చేయండి.',
        sendOtp: 'OTP పంపండి',
        phoneError: 'సరైన 10 అంకెల ఫోన్ నంబర్ నమోదు చేయండి',
        otpSent: 'OTP పంపబడింది',
        enterOtp: 'OTP నమోదు చేయండి',
        otpError: '6 అంకెల OTP నమోదు చేయండి',
        verify: 'ధృవీకరించి లాగిన్ అవ్వండి',
        resend: 'నంబర్ మార్చండి / OTP మళ్లీ పంపండి',
        verifying: 'OTP ధృవీకరించబడుతోంది...',
        footer: 'AWS Cognito ద్వారా సురక్షితం. OTP Twilio ద్వారా ధృవీకరించబడుతుంది.',
        sendFailed: 'OTP పంపడం విఫలమైంది',
        verifyFailed: 'ధృవీకరణ విఫలమైంది',
    },
    ta: {
        back: 'முகப்புக்கு திரும்பவும்',
        title: 'ஆபரேட்டர் உள்நுழைவு',
        desc: 'கிளெயிம் டாஷ்போர்டை அணுக உங்கள் பதிவு செய்யப்பட்ட தொலைபேசி எண்ணைப் பயன்படுத்தி உள்நுழைக.',
        sendOtp: 'OTP அனுப்பவும்',
        phoneError: 'சரியான 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்',
        otpSent: 'OTP அனுப்பப்பட்டது',
        enterOtp: 'OTP உள்ளிடவும்',
        otpError: '6 இலக்க OTP உள்ளிடவும்',
        verify: 'சரிபார்த்து உள்நுழைக',
        resend: 'எண்ணை மாற்றவும் / OTP மீண்டும் அனுப்பவும்',
        verifying: 'OTP சரிபார்க்கப்படுகிறது...',
        footer: 'AWS Cognito மூலம் பாதுகாக்கப்பட்டது. OTP Twilio மூலம் சரிபார்க்கப்படுகிறது.',
        sendFailed: 'OTP அனுப்ப முடியவில்லை',
        verifyFailed: 'சரிபார்ப்பு தோல்வியடைந்தது',
    },
    gu: {
        back: 'હોમ પર પાછા જાઓ',
        title: 'ઓપરેટર લોગિન',
        desc: 'ક્લેમ ડેશબોર્ડ મેળવવા માટે તમારા નોંધાયેલા ફોન નંબરથી સાઇન ઇન કરો.',
        sendOtp: 'OTP મોકલો',
        phoneError: 'માન્ય 10 અંકનો ફોન નંબર દાખલ કરો',
        otpSent: 'OTP મોકલવામાં આવ્યો',
        enterOtp: 'OTP દાખલ કરો',
        otpError: '6 અંકનો OTP દાખલ કરો',
        verify: 'ચકાસો અને લોગિન કરો',
        resend: 'નંબર બદલો / OTP ફરી મોકલો',
        verifying: 'OTP ચકાસાઈ રહ્યો છે...',
        footer: 'AWS Cognito દ્વારા સુરક્ષિત. OTP Twilio દ્વારા ચકાસાય છે.',
        sendFailed: 'OTP મોકલી શકાયો નહીં',
        verifyFailed: 'ચકાસણી નિષ્ફળ ગઈ',
    },
    kn: {
        back: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
        title: 'ಆಪರೇಟರ್ ಲಾಗಿನ್',
        desc: 'ಕ್ಲೈಮ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಲು ನಿಮ್ಮ ನೋಂದಾಯಿತ ಫೋನ್ ಸಂಖ್ಯೆಯಿಂದ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
        sendOtp: 'OTP ಕಳುಹಿಸಿ',
        phoneError: 'ಮಾನ್ಯ 10 ಅಂಕೆಯ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
        otpSent: 'OTP ಕಳುಹಿಸಲಾಗಿದೆ',
        enterOtp: 'OTP ನಮೂದಿಸಿ',
        otpError: '6 ಅಂಕೆಯ OTP ನಮೂದಿಸಿ',
        verify: 'ಪರಿಶೀಲಿಸಿ ಲಾಗಿನ್ ಮಾಡಿ',
        resend: 'ಸಂಖ್ಯೆ ಬದಲಿಸಿ / OTP ಮತ್ತೆ ಕಳುಹಿಸಿ',
        verifying: 'OTP ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
        footer: 'AWS Cognito ಮೂಲಕ ಸುರಕ್ಷಿತ. OTP ಅನ್ನು Twilio ಪರಿಶೀಲಿಸುತ್ತದೆ.',
        sendFailed: 'OTP ಕಳುಹಿಸಲು ವಿಫಲವಾಗಿದೆ',
        verifyFailed: 'ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ',
    },
}

export function getLoginCopy(language) {
    return LOGIN_COPY[language] || LOGIN_COPY.en
}
