import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'bms_dashboard_language'

export const SUPPORTED_LANGUAGES = [
    { code: 'en', label: 'English' },
    { code: 'hi', label: 'Hindi' },
    { code: 'mr', label: 'Marathi' },
    { code: 'te', label: 'Telugu' },
    { code: 'ta', label: 'Tamil' },
    { code: 'gu', label: 'Gujarati' },
    { code: 'kn', label: 'Kannada' },
]

const TRANSLATIONS = {
    en: {
        nav: {
            dashboard: 'Dashboard',
            access: 'Farmer Access',
            claims: 'Assisted Claims',
            analytics: 'Analytics',
            workspace: 'Claim Workspace',
        },
        common: {
            loading: 'Loading...',
            search_placeholder: 'Search claims...',
            change_language: 'Language',
            logout: 'Logout',
            save_section: 'Save section',
            save_missing_fields: 'Save missing fields',
            upload_document: 'Upload document',
            upload_photo: 'Upload photo',
            refresh: 'Refresh',
            verify: 'Verify',
            revoke: 'Revoke',
            request_access: 'Request access',
            create_claim: 'Create claim',
            submit_claim: 'Submit claim',
            generate_form: 'Generate form',
            generate_appeal: 'Generate appeal',
            delete_draft: 'Delete draft',
            select: 'Select',
            fields: 'fields',
            complete: 'complete',
            approved_only: 'Only approved photos are shown here.',
            hidden_rejected: '{count} rejected photo(s) hidden.',
            no_photos: 'No photo evidence yet.',
            no_documents: 'No documents uploaded yet.',
            no_pending_fields: 'No pending schema fields.',
            no_audit: 'No audit entries yet.',
            no_activity: 'No claim activity yet.',
            back_to_claims: 'Back to assisted claims',
        },
        dashboard: {
            consent_queue: 'Consent queue',
            open_access_center: 'Open access center',
            recent_assisted_claims: 'Recent assisted claims',
            open_queue: 'Open queue',
            no_pending_consent: 'No pending consent requests.',
            no_claims: 'No operator-visible claims yet.',
            accessible_farmers: 'Accessible Farmers',
            assisted_claims: 'Assisted Claims',
            pending_submission: 'Pending Submission',
            pending_access: 'Pending Access',
        },
        claims: {
            loading: 'Loading assisted claims...',
            search_placeholder: 'Search by farmer, phone, village, crop, claim ID...',
            all_statuses: 'All',
            farmer: 'Farmer',
            claim_id: 'Claim ID',
            village: 'Village',
            crop: 'Crop',
            status: 'Status',
            pending: 'Pending',
            deadline: 'Deadline',
            actions: 'Actions',
            open_workspace: 'Open workspace',
            unknown_farmer: 'Unknown farmer',
            no_matches: 'No accessible claims matched this filter.',
        },
        analytics: {
            loading: 'Loading analytics...',
            total_claims: 'Total Claims',
            active_farmers: 'Active Farmers',
            avg_completeness: 'Avg Completeness',
            rejection_rate: 'Rejection Rate',
            daily_claim_volume: 'Daily Claim Volume',
            claims_by_status: 'Claims by Status',
            claims_by_crop: 'Claims by Crop Type',
            claims: 'Claims',
        },
        access: {
            title: 'Farmer Access Center',
            subtitle: 'Verify farmer consent first. Once access is approved, you can view and edit the same claims the chatbot uses.',
            verified_farmers: 'Verified farmers',
            pending_requests: 'Pending requests',
            request_farmer_access: 'Request farmer access',
            access_requests: 'Access requests',
            verified_farmer_claims: 'Verified farmer claims',
            start_assisted_claim: 'Start assisted claim',
            no_access_requests: 'No farmer access requests yet.',
            pick_verified_farmer: 'Pick a verified farmer to view or resume claims.',
            no_claims_for_farmer: 'No claims yet for this farmer. Create one below.',
            verify_farmer_first: 'Verify a farmer first, then start a claim draft on their behalf.',
            claims_count: 'Claims',
            expires: 'Expires',
            farmer_otp: 'Farmer OTP',
            verified: 'verified',
            open_claims: 'Open claims',
            request_sent: 'Consent request sent. Enter the farmer OTP to verify access.',
        },
        claim: {
            tabs: {
                overview: 'Overview',
                farmer: 'Farmer',
                crop: 'Crop',
                dateLocation: 'Date & Location',
                documents: 'Documents',
                identity: 'Identity',
                missing: 'Missing Fields',
                photos: 'Photos',
                template: 'Insurer Form',
                review: 'Review & Submit',
                timeline: 'Status & Timeline',
            },
            photo_evidence: 'Photo evidence',
            photo_help: 'Upload and validate damage photos using the shared photo pipeline.',
            missing_fields: 'Missing fields',
            missing_help: 'Complete insurer-template fields that are still pending.',
            documents: 'Documents',
            documents_help: 'Upload farmer identity or supporting documents. Accepted documents are shared with the chatbot claim.',
            identity_verification: 'Identity verification',
            identity_help: 'Document name matching status for this farmer.',
            insurer_form: 'Insurer form',
            insurer_help: 'Select an insurer template, complete any pending fields, then generate the filled PDF.',
            choose_template: 'Choose template',
            review_pending_fields: 'Pending fields',
            review_documents: 'Documents',
            review_photos: 'Photos',
            review_identity: 'Identity',
            appeal_reason: 'Appeal reason',
            submitted_by_operator: 'Submitted by operator',
            submitted_at: 'Submitted at',
            identity_status: 'Status',
            claimed_name: 'Claimed name',
            extracted_name: 'Extracted name',
            source_document: 'Source document',
            workspace_unavailable: 'Claim data is unavailable.',
            save_success: '{section} saved.',
            missing_saved: 'Missing fields updated.',
            template_selected: 'Insurer template selected.',
            template_generated: 'Filled insurer form generated.',
            document_uploaded: 'Document uploaded and processed.',
            document_rejected: 'Document was not accepted.',
            photo_accepted: 'Photo evidence accepted.',
            photo_rejected: 'Photo was not accepted.',
        },
        fields: {
            farmerName: 'Farmer name',
            gender: 'Gender',
            socialCategory: 'Category',
            address: 'Address',
            phoneNumber: 'Phone number',
            aadhaarNumber: 'Aadhaar number',
            village: 'Village',
            district: 'District',
            state: 'State',
            cropType: 'Crop type',
            season: 'Season',
            cause: 'Cause of loss',
            areaHectares: 'Area (hectares)',
            policyType: 'Policy type',
            accountType: 'Account type',
            hasCropLoanOrKcc: 'Crop loan / KCC',
            lossDate: 'Loss date',
            exactLocation: 'Exact field location',
            gpsCoords: 'GPS coordinates',
            tehsil: 'Tehsil',
            pinCode: 'Pin code',
            notifiedAreaName: 'Notified area',
        },
        errors: {
            invalid_choice: 'Please choose one of the listed options.',
            invalid_date: 'Please enter a valid date.',
            future_loss_date: 'The loss date cannot be in the future.',
            invalid_number: 'Please enter a valid number.',
            positive_number_required: 'Please enter a value greater than zero.',
            invalid_phone: 'Please enter a valid phone number.',
            invalid_aadhaar: 'Aadhaar number must contain 12 digits.',
            invalid_ifsc: 'Please enter a valid IFSC code.',
            invalid_bank_account: 'Please enter a valid bank account number.',
            invalid_pin: 'Pin code must contain 6 digits.',
            invalid_value: 'Please enter a valid value.',
        },
    },
    hi: {
        nav: {
            dashboard: 'डैशबोर्ड',
            access: 'किसान एक्सेस',
            claims: 'सहायता प्राप्त क्लेम',
            analytics: 'एनालिटिक्स',
            workspace: 'क्लेम वर्कस्पेस',
        },
        common: {
            loading: 'लोड हो रहा है...',
            search_placeholder: 'क्लेम खोजें...',
            change_language: 'भाषा',
            logout: 'लॉगआउट',
            save_section: 'सेक्शन सेव करें',
            save_missing_fields: 'मिसिंग फील्ड्स सेव करें',
            upload_document: 'दस्तावेज़ अपलोड करें',
            upload_photo: 'फोटो अपलोड करें',
            refresh: 'रीफ्रेश',
            verify: 'सत्यापित करें',
            revoke: 'रद्द करें',
            request_access: 'एक्सेस मांगें',
            create_claim: 'क्लेम बनाएं',
            submit_claim: 'क्लेम सबमिट करें',
            generate_form: 'फॉर्म बनाएं',
            generate_appeal: 'अपील बनाएं',
            delete_draft: 'ड्राफ्ट हटाएं',
            select: 'चुनें',
            fields: 'फील्ड',
            complete: 'पूरा',
            approved_only: 'यहां केवल स्वीकृत फोटो दिखाई जाती हैं।',
            hidden_rejected: '{count} अस्वीकृत फोटो छिपाई गई हैं।',
            no_photos: 'अभी कोई फोटो प्रमाण नहीं है।',
            no_documents: 'अभी कोई दस्तावेज़ अपलोड नहीं हुआ है।',
            no_pending_fields: 'कोई लंबित स्कीमा फील्ड नहीं है।',
            no_audit: 'अभी कोई ऑडिट एंट्री नहीं है।',
            no_activity: 'अभी कोई क्लेम गतिविधि नहीं है।',
            back_to_claims: 'सहायता प्राप्त क्लेम पर वापस जाएं',
        },
        dashboard: {
            consent_queue: 'सहमति कतार',
            open_access_center: 'एक्सेस सेंटर खोलें',
            recent_assisted_claims: 'हाल के सहायता प्राप्त क्लेम',
            open_queue: 'कतार खोलें',
            no_pending_consent: 'कोई लंबित सहमति अनुरोध नहीं है।',
            no_claims: 'अभी कोई ऑपरेटर-क्लेम नहीं है।',
            accessible_farmers: 'उपलब्ध किसान',
            assisted_claims: 'सहायता प्राप्त क्लेम',
            pending_submission: 'लंबित सबमिशन',
            pending_access: 'लंबित एक्सेस',
        },
        claims: {
            loading: 'सहायता प्राप्त क्लेम लोड हो रहे हैं...',
            search_placeholder: 'किसान, फोन, गांव, फसल, क्लेम आईडी से खोजें...',
            all_statuses: 'सभी',
            farmer: 'किसान',
            claim_id: 'क्लेम आईडी',
            village: 'गांव',
            crop: 'फसल',
            status: 'स्थिति',
            pending: 'लंबित',
            deadline: 'अंतिम समय',
            actions: 'क्रियाएं',
            open_workspace: 'वर्कस्पेस खोलें',
            unknown_farmer: 'अज्ञात किसान',
            no_matches: 'इस फ़िल्टर से कोई क्लेम नहीं मिला।',
        },
        analytics: {
            loading: 'एनालिटिक्स लोड हो रहा है...',
            total_claims: 'कुल क्लेम',
            active_farmers: 'सक्रिय किसान',
            avg_completeness: 'औसत पूर्णता',
            rejection_rate: 'अस्वीकृति दर',
            daily_claim_volume: 'दैनिक क्लेम वॉल्यूम',
            claims_by_status: 'स्थिति के अनुसार क्लेम',
            claims_by_crop: 'फसल के अनुसार क्लेम',
            claims: 'क्लेम',
        },
        access: {
            title: 'किसान एक्सेस सेंटर',
            request_farmer_access: 'किसान एक्सेस मांगें',
            access_requests: 'एक्सेस अनुरोध',
            verified_farmer_claims: 'सत्यापित किसान क्लेम',
            start_assisted_claim: 'सहायता प्राप्त क्लेम शुरू करें',
            no_access_requests: 'अभी कोई किसान एक्सेस अनुरोध नहीं है।',
            pick_verified_farmer: 'क्लेम देखने या फिर से खोलने के लिए सत्यापित किसान चुनें।',
            no_claims_for_farmer: 'इस किसान के लिए अभी कोई क्लेम नहीं है।',
            verify_farmer_first: 'पहले किसान को सत्यापित करें, फिर क्लेम ड्राफ्ट शुरू करें।',
            claims_count: 'क्लेम',
            expires: 'समाप्ति',
            farmer_otp: 'किसान OTP',
            verified: 'सत्यापित',
            open_claims: 'क्लेम खोलें',
        },
        claim: {
            tabs: {
                overview: 'सारांश',
                farmer: 'किसान',
                crop: 'फसल',
                dateLocation: 'तारीख और स्थान',
                documents: 'दस्तावेज़',
                identity: 'पहचान',
                missing: 'मिसिंग फील्ड्स',
                photos: 'फोटो',
                template: 'बीमाकर्ता फॉर्म',
                review: 'समीक्षा और सबमिट',
                timeline: 'स्थिति और टाइमलाइन',
            },
            photo_evidence: 'फोटो प्रमाण',
            missing_fields: 'मिसिंग फील्ड्स',
            documents: 'दस्तावेज़',
            identity_verification: 'पहचान सत्यापन',
            insurer_form: 'बीमाकर्ता फॉर्म',
            choose_template: 'टेम्पलेट चुनें',
            review_pending_fields: 'लंबित फील्ड्स',
            review_documents: 'दस्तावेज़',
            review_photos: 'फोटो',
            review_identity: 'पहचान',
            appeal_reason: 'अपील का कारण',
            submitted_by_operator: 'ऑपरेटर द्वारा सबमिट',
            submitted_at: 'सबमिट समय',
            identity_status: 'स्थिति',
            claimed_name: 'दावा किया गया नाम',
            extracted_name: 'निकाला गया नाम',
            source_document: 'स्रोत दस्तावेज़',
            workspace_unavailable: 'क्लेम डेटा उपलब्ध नहीं है।',
            missing_saved: 'मिसिंग फील्ड्स अपडेट हो गईं।',
            template_selected: 'बीमाकर्ता टेम्पलेट चुना गया।',
            template_generated: 'भरा हुआ फॉर्म तैयार हो गया।',
            document_uploaded: 'दस्तावेज़ अपलोड और प्रोसेस हो गया।',
            document_rejected: 'दस्तावेज़ स्वीकार नहीं किया गया।',
            photo_accepted: 'फोटो प्रमाण स्वीकार किया गया।',
            photo_rejected: 'फोटो स्वीकार नहीं की गई।',
        },
        fields: {
            farmerName: 'किसान का नाम',
            gender: 'लिंग',
            socialCategory: 'श्रेणी',
            address: 'पता',
            phoneNumber: 'फोन नंबर',
            aadhaarNumber: 'आधार नंबर',
            village: 'गांव',
            district: 'जिला',
            state: 'राज्य',
            cropType: 'फसल प्रकार',
            season: 'सीजन',
            cause: 'नुकसान का कारण',
            areaHectares: 'क्षेत्र (हेक्टेयर)',
            policyType: 'पॉलिसी प्रकार',
            accountType: 'खाता प्रकार',
            hasCropLoanOrKcc: 'फसल ऋण / KCC',
            lossDate: 'नुकसान की तारीख',
            exactLocation: 'खेत का सही स्थान',
            gpsCoords: 'GPS निर्देशांक',
            tehsil: 'तहसील',
            pinCode: 'पिन कोड',
            notifiedAreaName: 'सूचित क्षेत्र',
        },
        errors: {
            invalid_choice: 'कृपया सूची में से सही विकल्प चुनें।',
            invalid_date: 'कृपया सही तारीख दर्ज करें।',
            future_loss_date: 'नुकसान की तारीख भविष्य में नहीं हो सकती।',
            invalid_number: 'कृपया सही संख्या दर्ज करें।',
            positive_number_required: 'कृपया शून्य से अधिक मान दर्ज करें।',
            invalid_phone: 'कृपया सही फोन नंबर दर्ज करें।',
            invalid_aadhaar: 'आधार नंबर 12 अंकों का होना चाहिए।',
            invalid_ifsc: 'कृपया सही IFSC कोड दर्ज करें।',
            invalid_bank_account: 'कृपया सही बैंक खाता संख्या दर्ज करें।',
            invalid_pin: 'पिन कोड 6 अंकों का होना चाहिए।',
            invalid_value: 'कृपया सही मान दर्ज करें।',
        },
    },
    mr: {
        nav: { dashboard: 'डॅशबोर्ड', access: 'शेतकरी प्रवेश', claims: 'सहाय्यित दावे', analytics: 'विश्लेषण', workspace: 'दावा कार्यक्षेत्र' },
        common: { loading: 'लोड होत आहे...', change_language: 'भाषा', logout: 'लॉगआउट', save_section: 'विभाग जतन करा', upload_photo: 'फोटो अपलोड करा', upload_document: 'दस्तऐवज अपलोड करा', approved_only: 'इथे फक्त मंजूर फोटो दिसतात.' },
        dashboard: { consent_queue: 'संमती रांग', recent_assisted_claims: 'अलीकडील सहाय्यित दावे', no_pending_consent: 'कोणतीही प्रलंबित संमती विनंती नाही.' },
        claims: { loading: 'सहाय्यित दावे लोड होत आहेत...', farmer: 'शेतकरी', village: 'गाव', crop: 'पीक', status: 'स्थिती', deadline: 'अंतिम मुदत', actions: 'क्रिया' },
        analytics: { loading: 'विश्लेषण लोड होत आहे...', total_claims: 'एकूण दावे', daily_claim_volume: 'दैनिक दावा प्रमाण', claims_by_status: 'स्थितीनुसार दावे', claims_by_crop: 'पिकानुसार दावे' },
        access: { title: 'शेतकरी प्रवेश केंद्र', request_farmer_access: 'शेतकरी प्रवेश मागा', access_requests: 'प्रवेश विनंत्या', verified_farmer_claims: 'सत्यापित शेतकरी दावे', start_assisted_claim: 'सहाय्यित दावा सुरू करा' },
        claim: { photo_evidence: 'फोटो पुरावा', documents: 'दस्तऐवज', identity_verification: 'ओळख पडताळणी', missing_fields: 'उर्वरित फील्ड्स', insurer_form: 'विमा फॉर्म' },
        fields: { farmerName: 'शेतकरी नाव', phoneNumber: 'फोन नंबर', aadhaarNumber: 'आधार नंबर', cropType: 'पीक प्रकार', season: 'हंगाम', cause: 'नुकसानीचे कारण', lossDate: 'नुकसान तारीख' },
    },
    te: {
        nav: { dashboard: 'డాష్‌బోర్డ్', access: 'రైతు యాక్సెస్', claims: 'సహాయక క్లెయిమ్‌లు', analytics: 'విశ్లేషణలు', workspace: 'క్లెయిమ్ వర్క్‌స్పేస్' },
        common: { loading: 'లోడ్ అవుతోంది...', change_language: 'భాష', logout: 'లాగ్ అవుట్', save_section: 'విభాగాన్ని సేవ్ చేయండి', upload_photo: 'ఫోటో అప్‌లోడ్ చేయండి', upload_document: 'పత్రాన్ని అప్‌లోడ్ చేయండి', approved_only: 'ఇక్కడ ఆమోదించిన ఫోటోలు మాత్రమే కనిపిస్తాయి.' },
        dashboard: { consent_queue: 'సమ్మతి క్యూ', recent_assisted_claims: 'ఇటీవలి సహాయక క్లెయిమ్‌లు' },
        claims: { loading: 'సహాయక క్లెయిమ్‌లు లోడ్ అవుతున్నాయి...', farmer: 'రైతు', village: 'గ్రామం', crop: 'పంట', status: 'స్థితి', deadline: 'గడువు', actions: 'చర్యలు' },
        analytics: { loading: 'విశ్లేషణలు లోడ్ అవుతున్నాయి...', total_claims: 'మొత్తం క్లెయిమ్‌లు', daily_claim_volume: 'రోజువారీ క్లెయిమ్ పరిమాణం', claims_by_status: 'స్థితి ప్రకారం క్లెయిమ్‌లు', claims_by_crop: 'పంట రకం ప్రకారం క్లెయిమ్‌లు' },
        access: { title: 'రైతు యాక్సెస్ సెంటర్', request_farmer_access: 'రైతు యాక్సెస్ అభ్యర్థించండి', access_requests: 'యాక్సెస్ అభ్యర్థనలు', verified_farmer_claims: 'ధృవీకరించిన రైతు క్లెయిమ్‌లు', start_assisted_claim: 'సహాయక క్లెయిమ్ ప్రారంభించండి' },
        claim: { photo_evidence: 'ఫోటో సాక్ష్యం', documents: 'పత్రాలు', identity_verification: 'గుర్తింపు ధృవీకరణ', missing_fields: 'మిస్సింగ్ ఫీల్డ్స్', insurer_form: 'ఇన్సూరర్ ఫారం' },
        fields: { farmerName: 'రైతు పేరు', phoneNumber: 'ఫోన్ నంబర్', aadhaarNumber: 'ఆధార్ నంబర్', cropType: 'పంట రకం', season: 'సీజన్', cause: 'నష్టానికి కారణం', lossDate: 'నష్టం తేదీ' },
    },
    ta: {
        nav: { dashboard: 'டாஷ்போர்டு', access: 'விவசாயி அணுகல்', claims: 'உதவியுடன் கிளெயிம்கள்', analytics: 'பகுப்பாய்வு', workspace: 'கிளெயிம் பணிப்பலகை' },
        common: { loading: 'ஏற்றப்படுகிறது...', change_language: 'மொழி', logout: 'வெளியேறு', save_section: 'பகுதியை சேமிக்கவும்', upload_photo: 'புகைப்படம் பதிவேற்றவும்', upload_document: 'ஆவணம் பதிவேற்றவும்', approved_only: 'இங்கே அங்கீகரிக்கப்பட்ட புகைப்படங்கள் மட்டும் காட்டப்படும்.' },
        dashboard: { consent_queue: 'ஒப்புதல் வரிசை', recent_assisted_claims: 'சமீபத்திய உதவியுடன் கிளெயிம்கள்' },
        claims: { loading: 'உதவியுடன் கிளெயிம்கள் ஏற்றப்படுகின்றன...', farmer: 'விவசாயி', village: 'கிராமம்', crop: 'பயிர்', status: 'நிலை', deadline: 'காலக்கெடு', actions: 'செயல்கள்' },
        analytics: { loading: 'பகுப்பாய்வு ஏற்றப்படுகிறது...', total_claims: 'மொத்த கிளெயிம்கள்', daily_claim_volume: 'தினசரி கிளெயிம் அளவு', claims_by_status: 'நிலைப்படி கிளெயிம்கள்', claims_by_crop: 'பயிர் வகைப்படி கிளெயிம்கள்' },
        access: { title: 'விவசாயி அணுகல் மையம்', request_farmer_access: 'விவசாயி அணுகலை கோருங்கள்', access_requests: 'அணுகல் கோரிக்கைகள்', verified_farmer_claims: 'சரிபார்க்கப்பட்ட விவசாயி கிளெயிம்கள்', start_assisted_claim: 'உதவியுடன் கிளெயிம் தொடங்குங்கள்' },
        claim: { photo_evidence: 'புகைப்பட சான்று', documents: 'ஆவணங்கள்', identity_verification: 'அடையாள சரிபார்ப்பு', missing_fields: 'குறைவுள்ள புலங்கள்', insurer_form: 'காப்பீட்டு படிவம்' },
        fields: { farmerName: 'விவசாயி பெயர்', phoneNumber: 'தொலைபேசி எண்', aadhaarNumber: 'ஆதார் எண்', cropType: 'பயிர் வகை', season: 'பருவம்', cause: 'இழப்புக்கான காரணம்', lossDate: 'இழப்பு தேதி' },
    },
    gu: {
        nav: { dashboard: 'ડેશબોર્ડ', access: 'ખેડૂત એક્સેસ', claims: 'સહાયિત ક્લેમ્સ', analytics: 'એનલિટિક્સ', workspace: 'ક્લેમ વર્કસ્પેસ' },
        common: { loading: 'લોડ થઈ રહ્યું છે...', change_language: 'ભાષા', logout: 'લૉગઆઉટ', save_section: 'વિભાગ સાચવો', upload_photo: 'ફોટો અપલોડ કરો', upload_document: 'દસ્તાવેજ અપલોડ કરો', approved_only: 'અહીં ફક્ત મંજૂર ફોટા જ દેખાશે.' },
        dashboard: { consent_queue: 'સંમતિ કતાર', recent_assisted_claims: 'તાજેતરના સહાયિત ક્લેમ્સ' },
        claims: { loading: 'સહાયિત ક્લેમ્સ લોડ થઈ રહ્યા છે...', farmer: 'ખેડૂત', village: 'ગામ', crop: 'પાક', status: 'સ્થિતિ', deadline: 'ડેડલાઇન', actions: 'ક્રિયાઓ' },
        analytics: { loading: 'એનલિટિક્સ લોડ થઈ રહ્યું છે...', total_claims: 'કુલ ક્લેમ્સ', daily_claim_volume: 'દૈનિક ક્લેમ વોલ્યુમ', claims_by_status: 'સ્થિતિ મુજબ ક્લેમ્સ', claims_by_crop: 'પાક પ્રકાર મુજબ ક્લેમ્સ' },
        access: { title: 'ખેડૂત એક્સેસ સેન્ટર', request_farmer_access: 'ખેડૂત એક્સેસ માંગો', access_requests: 'એક્સેસ વિનંતીઓ', verified_farmer_claims: 'ચકાસેલ ખેડૂત ક્લેમ્સ', start_assisted_claim: 'સહાયિત ક્લેમ શરૂ કરો' },
        claim: { photo_evidence: 'ફોટો પુરાવો', documents: 'દસ્તાવેજો', identity_verification: 'ઓળખ ચકાસણી', missing_fields: 'બાકી ફીલ્ડ્સ', insurer_form: 'વીમા ફોર્મ' },
        fields: { farmerName: 'ખેડૂતનું નામ', phoneNumber: 'ફોન નંબર', aadhaarNumber: 'આધાર નંબર', cropType: 'પાક પ્રકાર', season: 'સીઝન', cause: 'નુકસાનનું કારણ', lossDate: 'નુકસાન તારીખ' },
    },
    kn: {
        nav: { dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', access: 'ರೈತ ಪ್ರವೇಶ', claims: 'ಸಹಾಯಕ ದಾವೆಗಳು', analytics: 'ವಿಶ್ಲೇಷಣೆ', workspace: 'ದಾವೆ ವರ್ಕ್‌ಸ್ಪೇಸ್' },
        common: { loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', change_language: 'ಭಾಷೆ', logout: 'ಲಾಗ್ ಔಟ್', save_section: 'ವಿಭಾಗ ಉಳಿಸಿ', upload_photo: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', upload_document: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', approved_only: 'ಇಲ್ಲಿ ಅನುಮೋದಿತ ಫೋಟೋಗಳು ಮಾತ್ರ ತೋರುತ್ತವೆ.' },
        dashboard: { consent_queue: 'ಸಮ್ಮತಿ ಸರತಿ', recent_assisted_claims: 'ಇತ್ತೀಚಿನ ಸಹಾಯಕ ದಾವೆಗಳು' },
        claims: { loading: 'ಸಹಾಯಕ ದಾವೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...', farmer: 'ರೈತ', village: 'ಗ್ರಾಮ', crop: 'ಬೆಳೆ', status: 'ಸ್ಥಿತಿ', deadline: 'ಕೊನೆಯ ದಿನ', actions: 'ಕ್ರಿಯೆಗಳು' },
        analytics: { loading: 'ವಿಶ್ಲೇಷಣೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...', total_claims: 'ಒಟ್ಟು ದಾವೆಗಳು', daily_claim_volume: 'ದೈನಂದಿನ ದಾವೆ ಪ್ರಮಾಣ', claims_by_status: 'ಸ್ಥಿತಿಯಂತೆ ದಾವೆಗಳು', claims_by_crop: 'ಬೆಳೆ ಪ್ರಕಾರದ ದಾವೆಗಳು' },
        access: { title: 'ರೈತ ಪ್ರವೇಶ ಕೇಂದ್ರ', request_farmer_access: 'ರೈತ ಪ್ರವೇಶ ಕೇಳಿ', access_requests: 'ಪ್ರವೇಶ ವಿನಂತಿಗಳು', verified_farmer_claims: 'ಪರಿಶೀಲಿತ ರೈತ ದಾವೆಗಳು', start_assisted_claim: 'ಸಹಾಯಕ ದಾವೆ ಪ್ರಾರಂಭಿಸಿ' },
        claim: { photo_evidence: 'ಫೋಟೋ ಸಾಕ್ಷ್ಯ', documents: 'ದಾಖಲೆಗಳು', identity_verification: 'ಗುರುತು ಪರಿಶೀಲನೆ', missing_fields: 'ಬಾಕಿ ಕ್ಷೇತ್ರಗಳು', insurer_form: 'ವಿಮೆ ಫಾರ್ಮ್' },
        fields: { farmerName: 'ರೈತನ ಹೆಸರು', phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ', aadhaarNumber: 'ಆಧಾರ್ ಸಂಖ್ಯೆ', cropType: 'ಬೆಳೆ ಪ್ರಕಾರ', season: 'ಋತು', cause: 'ನಷ್ಟದ ಕಾರಣ', lossDate: 'ನಷ್ಟ ದಿನಾಂಕ' },
    },
}

const VALUE_TRANSLATIONS = {
    en: {
        Draft: 'Draft',
        Submitted: 'Submitted',
        Approved: 'Approved',
        Paid: 'Paid',
        Rejected: 'Rejected',
        'Evidence Pending': 'Evidence Pending',
        'Under Review': 'Under Review',
        'Survey Scheduled': 'Survey Scheduled',
        'Appeal Filed': 'Appeal Filed',
        wheat: 'Wheat',
        rice: 'Rice',
        cotton: 'Cotton',
        sugarcane: 'Sugarcane',
        soybean: 'Soybean',
        pulses: 'Pulses',
        maize: 'Maize',
        groundnut: 'Groundnut',
        mustard: 'Mustard',
        other: 'Other',
        kharif: 'Kharif',
        rabi: 'Rabi',
        zaid: 'Zaid',
        flood: 'Flood',
        drought: 'Drought',
        hail: 'Hail',
        unseasonal_rain: 'Unseasonal rain',
        pest: 'Pest attack',
        disease: 'Disease',
        fire: 'Fire',
        cyclone: 'Cyclone',
        frost: 'Frost',
        landslide: 'Landslide',
        pmfby: 'PMFBY',
        rwbcis: 'RWBCIS',
        yes: 'Yes',
        no: 'No',
        crop_loan: 'Crop loan',
        saving_account: 'Saving account',
        loanee: 'Loanee',
        non_loanee: 'Non loanee',
        SC: 'SC',
        ST: 'ST',
        OBC: 'OBC',
        OTHERS: 'Others',
        GEN: 'General',
        OTHER: 'Other',
        M: 'Male',
        F: 'Female',
        verified: 'Verified',
    },
    hi: {
        Draft: 'ड्राफ्ट',
        Submitted: 'सबमिट',
        Approved: 'स्वीकृत',
        Paid: 'भुगतान',
        Rejected: 'अस्वीकृत',
        'Evidence Pending': 'प्रमाण लंबित',
        'Under Review': 'समीक्षा में',
        'Survey Scheduled': 'सर्वे तय',
        'Appeal Filed': 'अपील दर्ज',
        wheat: 'गेहूं',
        rice: 'धान',
        cotton: 'कपास',
        sugarcane: 'गन्ना',
        soybean: 'सोयाबीन',
        pulses: 'दालें',
        maize: 'मक्का',
        groundnut: 'मूंगफली',
        mustard: 'सरसों',
        other: 'अन्य',
        kharif: 'खरीफ',
        rabi: 'रबी',
        zaid: 'जायद',
        flood: 'बाढ़',
        drought: 'सूखा',
        hail: 'ओले',
        unseasonal_rain: 'बेमौसम बारिश',
        pest: 'कीट प्रकोप',
        disease: 'रोग',
        fire: 'आग',
        cyclone: 'चक्रवात',
        frost: 'पाला',
        landslide: 'भूस्खलन',
        yes: 'हाँ',
        no: 'नहीं',
        crop_loan: 'फसल ऋण',
        saving_account: 'बचत खाता',
        loanee: 'लोनधारक',
        non_loanee: 'गैर-लोनधारक',
        verified: 'सत्यापित',
    },
}

function resolvePath(source, path) {
    return path.split('.').reduce((current, part) => current?.[part], source)
}

function interpolate(template, values = {}) {
    return Object.entries(values).reduce(
        (result, [key, value]) => result.replace(new RegExp(`\\{${key}\\}`, 'g'), String(value)),
        template
    )
}

function humanize(value) {
    return String(value || '')
        .replace(/_/g, ' ')
        .replace(/\b\w/g, (char) => char.toUpperCase())
}

const LanguageContext = createContext(null)

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (!context) throw new Error('useLanguage must be used within LanguageProvider')
    return context
}

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(() => {
        const stored = localStorage.getItem(STORAGE_KEY)
        return SUPPORTED_LANGUAGES.some((item) => item.code === stored) ? stored : 'en'
    })

    useEffect(() => {
        localStorage.setItem(STORAGE_KEY, language)
        document.documentElement.lang = language
    }, [language])

    const value = useMemo(() => {
        const t = (path, vars = {}) => {
            const translated = resolvePath(TRANSLATIONS[language], path) ?? resolvePath(TRANSLATIONS.en, path) ?? path
            return typeof translated === 'string' ? interpolate(translated, vars) : translated
        }

        const translateValue = (valueToTranslate) => (
            VALUE_TRANSLATIONS[language]?.[valueToTranslate]
            || VALUE_TRANSLATIONS.en?.[valueToTranslate]
            || humanize(valueToTranslate)
        )

        const translateField = (fieldKey, fallback = '') => {
            const translated = resolvePath(TRANSLATIONS[language], `fields.${fieldKey}`)
                ?? resolvePath(TRANSLATIONS.en, `fields.${fieldKey}`)
            return translated || fallback || humanize(fieldKey)
        }

        return {
            language,
            setLanguage,
            languages: SUPPORTED_LANGUAGES,
            t,
            translateValue,
            translateField,
        }
    }, [language])

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    )
}
